--- #YAML:1.0
name:               Spreadsheet-WriteExcel
version:            2.37
abstract:           Write to a cross platform Excel binary file
author:
    - John McNamara (jmcnamara@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Temp:         0
    OLE::Storage_Lite:  0.19
    Parse::RecDescent:  0
resources:
    MailingList:  http://groups.google.com/group/spreadsheet-writeexcel
    repository:   http://github.com/jmcnamara/spreadsheet-writeexcel
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
